# -*- coding: utf-8 -*-
"""vietTTS notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oczrWOQOr1Y_qLdgis1twSlNZlfPVXoY

### Quick start
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/NTT123/vietTTS.git
# %cd /content/vietTTS
!pip3 install -e .
!bash ./scripts/quick_start.sh
from google.colab import output
output.clear()

text = """
Đoạn trường tân thanh, thường được biết đến với cái tên đơn giản là Truyện Kiều, là một truyện thơ của đại thi hào Nguyễn Du. 
Đây được xem là truyện thơ nổi tiếng nhất và xét vào hàng kinh điển trong văn học Việt Nam.
Câu chuyện dựa theo tiểu thuyết Kim Vân Kiều truyện của Thanh Tâm Tài Nhân, một thi sĩ thời nhà Minh, Trung Quốc.
Tác phẩm kể lại cuộc đời, những thử thách và đau khổ của Thúy Kiều, một phụ nữ trẻ xinh đẹp và tài năng, phải hy sinh thân mình để cứu gia đình. 
Để cứu cha và em trai khỏi tù, cô bán mình kết hôn với một người đàn ông trung niên, không biết rằng anh ta là một kẻ buôn người, và bị ép làm kĩ nữ trong lầu xanh.
"""
!python3 -m vietTTS.synthesizer --lexicon-file assets/infore/lexicon.txt --text="{text}" --output=clip.wav --silence-duration 0.2
import IPython.display as ipd
ipd.Audio('clip.wav')

"""# Train duration model and acoustic model"""

!bash ./scripts/download_aligned_infore_dataset.sh

!python3 -m vietTTS.nat.duration_trainer

!python3 -m vietTTS.nat.acoustic_trainer

"""# Train HiFiGAN vocoder"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/vietTTS
!bash ./scripts/download_aligned_infore_dataset.sh

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/jik876/hifi-gan.git
# %cd hifi-gan
!ln -sf /content/vietTTS/train_data /content/vietTTS/hifi-gan/data
!cd data;  ls -1 *.TextGrid| sed -e 's/\.TextGrid$//' > /content/vietTTS/hifi-gan/files.txt
!head -n 100 ./files.txt > val_files.txt
!tail -n +101 files.txt > train_files.txt
!cp /content/vietTTS/assets/hifigan/config.json ./config.json

!python3 train.py --config config.json --input_wavs_dir=data  --input_training_file=train_files.txt  --input_validation_file=val_files.txt